name: mycs_web
description: "MyCS web application"
publish_to: none

version: 0.0.1+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logging: ^1.2.0

  amplify_flutter: ^1.6.0
  amplify_auth_cognito: ^1.6.0

  cloud_auth_feature:
    path: ../../../libs/shared/feature/flutter/cloud_auth
  cloud_profile_feature:
    path: ../../../libs/shared/feature/flutter/cloud_profile

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
